Lesson7(11_12_23)/BootcampEf/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BootcampEf.Models;

namespace BootcampEf.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Lesson7(11_12_23)/BootcampEf/Controllers/KursController.cs
using Microsoft.AspNetCore.Mvc;
using BootcampEf.Data;
using Microsoft.EntityFrameworkCore;
namespace BootcampEf.Controllers
{
    public class KursController : Controller
    {
        private readonly DataContext _context;
        public KursController(DataContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Kurslar.ToListAsync());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Kurs model)
        {
            _context.Kurslar.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kurs = await _context.Kurslar
            .Include(k=>k.KursKayitlari)
            .ThenInclude(k=>k.Ogrenci)
            .FirstOrDefaultAsync(k=>k.KursId==id);
            //var ogr = await _context.Ogrenciler.FirstOrDefaultAsync(o => o.OgrenciId == id);

            if (kurs == null)
            {
                return NotFound();
            }

            return View(kurs);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int? id, Kurs model)
        {
            if (id != model.KursId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateException)
                {
                    if (!_context.Ogrenciler.Any(o => o.OgrenciId == model.KursId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }
          [HttpGet]
        public async Task<IActionResult> Delete(int? id){
            if(id == null){
                return NotFound();
            }
            var kurs = await _context.Kurslar.FindAsync(id);

            if(kurs == null){
                return NotFound();
            }    
            return View(kurs);
        }
        [HttpPost]

        //Model Biding işlemi yaptık.
        //Tag helper kullanacaksak model biding yapmak lazım
        public async Task<IActionResult> Delete([FromForm]int id){
            var kurs = await _context.Kurslar.FindAsync(id);
            if(kurs==null){
                return NotFound();
            }
            _context.Kurslar.Remove(kurs);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Lesson7(11_12_23)/BootcampEf/Controllers/KursKayitController.cs
using BootcampEf.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BootcampEf.Controllers
{
    public class KursKayitController : Controller
    {
        private readonly DataContext _context;
        public KursKayitController(DataContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var kursKayitlari = await _context.KursKayitlari
            .Include(x => x.Ogrenci)
            .Include(x => x.Kurs)
            .ToListAsync();
            return View(kursKayitlari);
        }
        public async Task<IActionResult> Create()
        {
            ViewBag.Ogrenciler = new SelectList(await _context.Ogrenciler.ToListAsync(), "OgrenciId", "AdSoyad");
            ViewBag.Kurslar = new SelectList(await _context.Kurslar.ToListAsync(), "KursId", "Baslik");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(KursKayit model)
        {
            model.KayitTarihi = DateTime.Now;
            _context.KursKayitlari.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Lesson7(11_12_23)/BootcampEf/Controllers/OgrenciController.cs
using BootcampEf.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BootcampEf.Controllers
{
    public class OgrenciController : Controller{
        
        private readonly DataContext _context;
        public OgrenciController(DataContext context){
            _context = context;
        }


        public async Task<IActionResult> Index(){          
            return View(await _context.Ogrenciler.ToListAsync());
        }

        public IActionResult Create(){
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Ogrenci model){
            _context.Ogrenciler.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int? id){
            if(id==null){
                return NotFound();
            }
            
            var ogr = await _context.Ogrenciler
            .Include(o=>o.KursKayitlari)
            .ThenInclude(o=>o.Kurs)
            .FirstOrDefaultAsync(o=>o.OgrenciId ==id);
            //var ogr = await _context.Ogrenciler.FirstOrDefaultAsync(o => o.OgrenciId == id);

            if(ogr == null){
                return NotFound();
            }

            return View(ogr);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int? id, Ogrenci model){

            if(id != model.OgrenciId){
                return NotFound();
            }
            if(ModelState.IsValid){
                try{
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }catch(DbUpdateConcurrencyException){
                    if(!_context.Ogrenciler.Any(o => o.OgrenciId == model.OgrenciId)){
                        return NotFound();
                    }else{
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }

            return View(model);
            
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id){
            if(id == null){
                return NotFound();
            }
            var ogrenci = await _context.Ogrenciler.FindAsync(id);

            if(ogrenci == null){
                return NotFound();
            }    
            return View(ogrenci);
        }
        [HttpPost]

        //Model Biding işlemi yaptık.
        //Tag helper kullanacaksak model biding yapmak lazım
        public async Task<IActionResult> Delete([FromForm]int id){
            var ogrenci = await _context.Ogrenciler.FindAsync(id);
            if(ogrenci==null){
                return NotFound();
            }
            _context.Ogrenciler.Remove(ogrenci);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Lesson7(11_12_23)/BootcampEf/Views/Kurs/Create.cshtml
@model Kurs

<h2>Kurs Ekle</h2>

<form asp-controller="Kurs" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Baslik" class="form-label">Kurs Adı</label>
        <input asp-for="Baslik" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary">Kaydet</button>

</form>

Lesson7(11_12_23)/BootcampEf/Views/Kurs/Delete.cshtml
@model Kurs
<p>
    <b>@Model.Baslik </b> isimli bootcampi silmek istiyor musun?
    <form asp-action="Delete" method="post">
        <input type="hidden" value="@Model.KursId" name="id">
        <button type="submit" class="btn btn-danger">Evet</button>
        <button asp-action="Index" type="submit" class="btn btn-primary">Hayır</button>
    </form>
</p>

Lesson7(11_12_23)/BootcampEf/Views/Kurs/Edit.cshtml
@model Kurs

<h2>Kurs Güncelle</h2>
<hr>

<div class="row">
    <div class="col-8">
        <form asp-controller="Kurs" asp-action="Edit" method="post">
            <input type="hidden" asp-for="KursId">
            <div class="mb-3">
                <label asp-for="Baslik" class="form-label">Kurs Adı</label>
                <input asp-for="Baslik" class="form-control">
            </div>

            <button type="submit" class="btn btn-primary">Kaydet</button>

        </form>
    </div>
    <div class="col-4">
        <h4>Kayıtlı Öğrenciler</h4>
        <hr>
        <ul>
            @foreach (var item in @Model.KursKayitlari)
            {
                <li>@item.Ogrenci.AdSoyad</li>
            }
        </ul>
    </div>
</div>

Lesson7(11_12_23)/BootcampEf/Views/Kurs/Index.cshtml
@model IEnumerable<Kurs>

<h2>Kurs Listesi</h2>
<a href="/Kurs/Create" class="btn btn-primary">Kurs Ekle</a>
<hr>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(m => m.KursId)</th>
            <th>@Html.DisplayNameFor(m => m.Baslik)</th>
            <th style="width: 150px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.KursId)</td>
                <td>@Html.DisplayFor(modelItem => item.Baslik)</td>
               
                <td>
                    <a asp-action="Edit" asp-route-id="@item.KursId" class="btn btn-sm btn-primary">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.KursId" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Lesson7(11_12_23)/BootcampEf/Views/KursKayit/Create.cshtml
@model KursKayit

<h2>Kurs Kayıt Ekle</h2>

<form asp-controller="KursKayit" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="OgrenciId" class="form-label">Öğrenci</label>
        <select asp-items="ViewBag.Ogrenciler" asp-for="OgrenciId" class="form-control">
            <option value="">Seçiniz</option>
        </select>

    </div>
    <div class="mb-3">
        <label asp-for="KursId" class="form-label">Kurs</label>
        <select asp-items="ViewBag.Kurslar" asp-for="KursId" class="form-control">
            <option value="">Seçiniz</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Kaydet</button>

</form>

Lesson7(11_12_23)/BootcampEf/Views/KursKayit/Index.cshtml
@model IEnumerable<KursKayit>

    <h2>Öğrenci Listesi</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th style="width: 150px;">@Html.DisplayNameFor(m=>m.KayitId)</th>
                <th >@Html.DisplayNameFor(m=>m.Ogrenci.OgrenciAd)</th>
                <th>@Html.DisplayNameFor(m=>m.Kurs.Baslik)</th>
                <th style="width: 150px;"></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model){
            <tr>
                <td>@Html.DisplayFor(modelItem => item.KayitId)</td>
                <td>@Html.DisplayFor(modelItem => item.Ogrenci.OgrenciAd)</td>
                <td>@Html.DisplayFor(modelItem => item.Kurs.Baslik)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.OgrenciId" class="btn btn-primary">Edit</a>
                    <a asp-action="Edit" asp-route-id="@item.OgrenciId" class="btn btn-danger">Delete</a>
                </td>
            </tr>
            }
        </tbody>
    </table>

Lesson7(11_12_23)/BootcampEf/Views/Ogrenci/Create.cshtml
@model Ogrenci

<h2>Öğrenci Ekle</h2>

<form asp-controller="Ogrenci" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="OgrenciAd" class="form-label">Öğrenci Adı</label>
        <input asp-for="OgrenciAd" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="OgrenciSoyad" class="form-label">Öğrenci Soyadı</label>
        <input asp-for="OgrenciSoyad" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Eposta" class="form-label">E Posta</label>
        <input asp-for="Eposta" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Telefon" class="form-label">Telefon Numarası</label>
        <input asp-for="Telefon" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary">Kaydet</button>

</form>

Lesson7(11_12_23)/BootcampEf/Views/Ogrenci/Delete.cshtml
@model Ogrenci
<p>
    <b>@Model.OgrenciAd @Model.OgrenciSoyad</b> isimli öğrenciyi silmek istiyor musun?
    <form asp-action="Delete" method="post">
        <input type="hidden" value="@Model.OgrenciId" name="id">
        <button type="submit" class="btn btn-danger">Evet</button>
        <button asp-action="Index" type="submit" class="btn btn-primary">Hayır</button>
    </form>
</p>

Lesson7(11_12_23)/BootcampEf/Views/Ogrenci/Edit.cshtml
@model Ogrenci

<h2>Öğrenci Güncelle</h2>

<div class="row">

    <div class="col-8">
        <form asp-controller="Ogrenci" asp-action="Edit" method="post">
            <input type="hidden" asp-for="OgrenciId">
            <div class="mb-3">
                <label asp-for="OgrenciAd" class="form-label">Öğrenci Adı</label>
                <input asp-for="OgrenciAd" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="OgrenciSoyad" class="form-label">Öğrenci Soyadı</label>
                <input asp-for="OgrenciSoyad" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Eposta" class="form-label">E Posta</label>
                <input asp-for="Eposta" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Telefon" class="form-label">Telefon Numarası</label>
                <input asp-for="Telefon" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Kaydet</button>

        </form>
    </div>
    <div class="col-4">
        <h4>Kayıtlı Bootcampler</h4>
        <hr>
        <ul>
            @foreach(var item in @Model.KursKayitlari){
                <li>@item.Kurs.Baslik</li>
            }
        </ul>
    </div>
</div>

Lesson7(11_12_23)/BootcampEf/Views/Ogrenci/Index.cshtml
@model IEnumerable<Ogrenci>

<h2>Öğrenci Listesi</h2>
<a href="/Ogrenci/Create" class="btn btn-primary">Öğrenci Ekle</a>
<hr>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(m => m.OgrenciId)</th>
            <th>@Html.DisplayNameFor(m => m.OgrenciAd)</th>
            <th>@Html.DisplayNameFor(m => m.OgrenciSoyad)</th>
            <th>@Html.DisplayNameFor(m => m.Eposta)</th>
            <th>@Html.DisplayNameFor(m => m.Telefon)</th>
            <th style="width: 150px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.OgrenciId)</td>
                <td>@Html.DisplayFor(modelItem => item.OgrenciAd)</td>
                <td>@Html.DisplayFor(modelItem => item.OgrenciSoyad)</td>
                <td>@Html.DisplayFor(modelItem => item.Eposta)</td>
                <td>@Html.DisplayFor(modelItem => item.Telefon)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.OgrenciId" class="btn btn-sm btn-primary">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.OgrenciId" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Lesson7(11_12_23)/BootcampEf/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BootcampEf</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BootcampEf.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BootcampEf</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ogrenci" asp-action="Index">Öğrenci</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kurs" asp-action="Index">Kurs</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="KursKayit" asp-action="Index">Kurs Kayıt</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BootcampEf - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>