Lesson9(14_12_23)/BootcampEf/Controllers/OgretmenController.cs
using BootcampEf.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BootcampEf.Controllers
{
    public class OgretmenController: Controller
    {
        private readonly DataContext _context;
        public OgretmenController(DataContext context)
        {
            _context = context;
        }

         public async Task<IActionResult> Index()
        {
            return View(await _context.Ogretmenler.ToListAsync());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Ogretmen model)
        {
            _context.Ogretmenler.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

         [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var entity = await _context
                                .Ogretmenler
                                .FirstOrDefaultAsync(o => o.OgretmenId == id);

            if(entity == null) 
            {
                return NotFound();
            }

            return View(entity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Ogretmen model)
        {
            if(id != model.OgretmenId)
            {
                return NotFound();
            }

            if(ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch(DbUpdateConcurrencyException)
                {
                    if(!_context.Ogretmenler.Any(o => o.OgretmenId == model.OgretmenId))
                    {
                        return NotFound();
                    } 
                    else 
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var entity = await _context.Ogretmenler.FindAsync(id);

            if(entity == null)
            {
                return NotFound();
            }

            return View(entity);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromForm]int id)
        {
            var entity = await _context.Ogretmenler.FindAsync(id);
            if(entity == null)
            {
                return NotFound();
            }
            _context.Ogretmenler.Remove(entity);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }



    }
}

Lesson9(14_12_23)/BootcampEf/Views/Ogretmen/Create.cshtml
@model Ogretmen

<h2>Öğretmen Ekle</h2>
<hr>
<form asp-controller="Ogretmen" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Ad" class="form-label">Öğretmen Adı</label>
        <input asp-for="Ad" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Soyad" class="form-label">Öğretmen Soyad</label>
        <input asp-for="Soyad" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Eposta" class="form-label">Eposta</label>
        <input asp-for="Eposta" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Telefon" class="form-label">Telefon</label>
        <input asp-for="Telefon" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="BaslamaTarihi" class="form-label">Başlama Tarihi</label>
        <input asp-for="BaslamaTarihi" class="form-control">
    </div>

    <button type="submit" class="btn btn-secondary">Kaydet</button>

</form>

Lesson9(14_12_23)/BootcampEf/Views/Ogretmen/Delete.cshtml
@model Ogretmen

<p>
    <b> @Model.Ad @Model.Soyad</b> isimli öğrenciyi silmek istiyor musunuz?

    <form asp-action="Delete" method="post">
        <input type="hidden" value="@Model.OgretmenId" name="id">
        <button type="submit" class="btn btn-danger">Evet</button>
        <a asp-action="Index" class="btn btn-primary">Hayır</a>
    </form>
</p>

Lesson9(14_12_23)/BootcampEf/Views/Ogretmen/Edit.cshtml
@model Ogretmen

<h2>Öğretmen Güncelleme</h2>
<hr>

<div class="row">
    <div class="col-8">
        <form asp-controller="Ogretmen" asp-action="Edit" method="post">
            <input type="hidden" asp-for="OgretmenId">
            <div class="mb-3">
                <label asp-for="Ad" class="form-label">Öğretmen Adı</label>
                <input asp-for="Ad" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Soyad" class="form-label">Öğretmen Soyad</label>
                <input asp-for="Soyad" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Eposta" class="form-label">Eposta</label>
                <input asp-for="Eposta" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Telefon" class="form-label">Telefon</label>
                <input asp-for="Telefon" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="BaslamaTarihi" class="form-label">Başlama Tarihi</label>
                <input asp-for="BaslamaTarihi" class="form-control">
            </div>
        
            <button type="submit" class="btn btn-secondary">Kaydet</button>
        
        </form>
    </div>
    <div class="col-4">

    </div>
</div>

Lesson9(14_12_23)/BootcampEf/Views/Ogretmen/Index.cshtml
@model IEnumerable<Ogretmen>

<h2>Öğrenci Listesi</h2>
<a href="/Ogretmen/Create" class="btn btn-primary">Öğretmen Ekle</a>
<hr>
<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width: 150px;">@Html.DisplayNameFor(m => m.OgretmenId)</th>
            <th>@Html.DisplayNameFor(m => m.Ad)</th>
            <th>@Html.DisplayNameFor(m => m.Soyad)</th>
            <th>@Html.DisplayNameFor(m => m.BaslamaTarihi)</th>
            <th style="width: 150px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.OgretmenId)</td>
                <td>@Html.DisplayFor(modelItem => item.Ad)</td>
                <td>@Html.DisplayFor(modelItem => item.Soyad)</td>
                <td>@Html.DisplayFor(modelItem => item.BaslamaTarihi)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.OgretmenId" class="btn btn-sm btn-primary">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.OgretmenId" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }

    </tbody>
</table>