Lesson6(7_12_23)/BootcampApp/Models/Bootcamp.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BootcampApp.Models
{
    public class Bootcamp
    {
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? Image {get;set;}
        public string? Description { get; set; }

        public string[]? Tags {get;set;}
        public bool isActive{get;set;}
        public bool isHome { get; set; }
    }
}

Lesson6(7_12_23)/BootcampApp/Models/ErrorViewModel.cs
namespace BootcampApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Lesson6(7_12_23)/BootcampApp/Models/Repository.cs
using System.Net.Http.Headers;

namespace BootcampApp.Models{

    public class Repository{

        private static readonly List<Bootcamp> _bootcamp = new();

        static Repository(){
            _bootcamp = new List<Bootcamp>(){
                new Bootcamp(){
                Id = 1,Title="Full Stack Bootcamp",Image="1.jpg",Description="Html,css,javascript ve Asp.net dersleri",Tags=new string[]{"html","css","aspnet core"},isActive = true,isHome=true},
            new Bootcamp(){
                Id = 2,Title="Game Bootcamp",Image="2.jpg",Description="Unity ile mobil oyun geliştirme",Tags=new string[]{"unity","game","csharp"},isActive = true,isHome=true},
             new Bootcamp(){
                Id = 3,Title="SQL Bootcamp",Image="3.jpg",Description="SQL Server kullanımı",Tags=new string[]{"sql server","tsql"},isActive = true,isHome=true
            },
             new Bootcamp(){
                Id = 4,Title="Backend Bootcamp",Image="4.jpg",Description="Arkaplanda Web Geliştirme",Tags=new string[]{"mvc","dotnet core","aspnet core"},isActive = true,isHome=true
            }
            };
        }
    public static List<Bootcamp> Bootcamps{
        get{
            return _bootcamp;
        }
    }
    public static Bootcamp? GetById(int? id){
        return _bootcamp.FirstOrDefault(b=>b.Id == id);
    }
    }
}

Lesson6(7_12_23)/BootcampApp/Controllers/BootcampController.cs
using BootcampApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace BootcampApp.Controllers;
public class BootcampController : Controller
{   
    public IActionResult Details(int? id)
    {
        if(id==null){
            return Redirect("/Bootcamp/List");
        }
        var kurs = Repository.GetById(id);
        return View(kurs);
    }
    public IActionResult List()
    {
        return View(Repository.Bootcamps);
    }
}

Lesson6(7_12_23)/BootcampApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BootcampApp.Models;

namespace BootcampApp.Controllers;

public class HomeController : Controller
{

    public IActionResult Index()
    {
        return View(Repository.Bootcamps);
    
    }
    
}

Lesson6(7_12_23)/BootcampApp/Views/Bootcamp/Details.cshtml
@model Bootcamp
<div class="row">
    <div class="col-md-4">
        <img src="~/img/@Model.Image" class="img-fluid rounded-start" alt="My image" />
    </div>
    <div class="col-md-8">
        <div class="card-body">
            <a asp-controller="Bootcamp" asp-action="Details" asp-route-id="@Model.Id">
                <h3>@Model.Title</h3>
            </a>
            <p>@Model.Description</p>
        </div>
        <div>
            @if (Model.Tags != null)
            {
                @foreach (var tag in Model.Tags)
                {
                    <span class="badge bg-danger">@tag</span>
                }
            }
        </div>
    </div>
</div>

Lesson6(7_12_23)/BootcampApp/Views/Bootcamp/list.cshtml
@model List<Bootcamp>
@foreach (var kurs in Model)
{
    @await Html.PartialAsync("_List",kurs)
}

Lesson6(7_12_23)/BootcampApp/Views/Home/Index.cshtml
@model List<Bootcamp>

@section About{
@await Html.PartialAsync("_About")  
}

<div class="row">
    @foreach(var kurs in Model){
        @if(kurs.isHome && kurs.isActive){
        <div class="col-3">
            <div class="card">
                <img src="~/img/@kurs.Image" alt="My Picture">
                <div class="card-body">
                    <h5 class="card-title">@kurs.Title</h5>
                    <p class="card-text">@kurs.Description</p>
                    <a class="btn btn-danger" asp-controller="Bootcamp" asp-action="Details" asp-route-id="@kurs.Id">Detay</a>
                </div>
            </div>
        </div>
        }
    }
</div>